# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161121_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='wallColor',
            field=models.CharField(default=0.0, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='dimX',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='dimY',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='dimZ',
            field=models.FloatField(),
        ),
    ]
