# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20161121_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='furniture',
            field=models.TextField(default=b''),
        ),
    ]
